### PR TITLE
Update to current JSON Api

### PR DESCRIPTION
**Pull request by mkh1973**

### CODE REVIEW

**Comment by mkh1973** [comment]
Done and also changed component status when recovery underway

**Comment by 2Belette** [comment]
I still got the issue where the incident is not cleared when Partial Outage -> Normal, is it working on your side?

**Comment by mkh1973** [comment]
Hi!

no, not properly; i have to investigate further.

br Michael

**Comment by 2Belette** [comment]
ok
opening an issue #12  then as I think we are not the only one...don't hesitate to comment if needed

**Pull request merged**
